CREATE SEQUENCE ADDRESS_ID_SEQ
increment by 1
start with 1
maxvalue 150
nocache
nocycle;

CREATE TABLE ADDRESS_TB1(
ADDR_ID NUMBER(3) PRIMARY KEY,
ADDR_LINE1 VARCHAR2(30),
ADDR_LINE2 VARCHAR2(30),
ADDR_LINE3 VARCHAR2(30),
CITY VARCHAR2(15),
STATE VARCHAR2(15)
);

INSERT INTO ADDRESS_TB1 VALUES (ADDRESS_ID_SEQ.NEXTVAL, '123 Main St', 'Apt 4B', 'ITC STOCK', 'CHENNAI', 'TAMIL NADU');
INSERT INTO ADDRESS_TB1 VALUES (ADDRESS_ID_SEQ.NEXTVAL, '456 Park Ave', 'Suite 502', 'UTS', 'BENGALURU', 'KARNATAKA');
INSERT INTO ADDRESS_TB1 VALUES (ADDRESS_ID_SEQ.NEXTVAL, '521 Ponneri', 'Velammal College Opp', 'Park Nearby', 'TIRUVALLUR', 'TAMIL NADU');
INSERT INTO ADDRESS_TB1 VALUES (ADDRESS_ID_SEQ.NEXTVAL, '789 Greenway St', 'Block C', 'Near Mall', 'COIMBATORE', 'TAMIL NADU');
INSERT INTO ADDRESS_TB1 VALUES (ADDRESS_ID_SEQ.NEXTVAL, '101 Tech Road', 'Floor 3', 'XYZ Tower', 'HYDERABAD', 'TELANGANA');
INSERT INTO ADDRESS_TB1 VALUES (ADDRESS_ID_SEQ.NEXTVAL, '33 Taramani Road', 'Svh hostel', 'Near by RailwayStation', 'CHENNAI', 'TAMIL NADU');

CREATE SEQUENCE CUSTOMER_ID_SEQ
increment by 1
start with 1
maxvalue 150
nocache
nocycle;


CREATE TABLE CUSTOMER_TB1(
CUST_ID NUMBER(3) PRIMARY KEY,
CUST_NAME VARCHAR2(20),
PHONE NUMBER(10),
EMAIL VARCHAR2(25),
ADDR_ID,
CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY(ADDR_ID)
REFERENCES ADDRESS_TB1 (ADDR_ID)
);
INSERT INTO CUSTOMER_TB1(CUST_ID, CUST_NAME, PHONE, EMAIL, ADDR_ID) VALUES (CUSTOMER_ID_SEQ.NEXTVAL, 'Praveenkishore',9360296627,'Praveen123@gmail.com',3);
INSERT INTO CUSTOMER_TB1(CUST_ID, CUST_NAME, PHONE, EMAIL, ADDR_ID) VALUES (CUSTOMER_ID_SEQ.NEXTVAL, 'PreamKumar P',3245789215,'Premkumar52@gmail.com',1);
INSERT INTO CUSTOMER_TB1 VALUES (CUSTOMER_ID_SEQ.NEXTVAL, 'Ravi Shankar', 9876543210, 'ravi.s@example.com', 2);
INSERT INTO CUSTOMER_TB1 VALUES (CUSTOMER_ID_SEQ.NEXTVAL, 'Samantha R', 8765432109, 'sam.r@example.com', 4);
INSERT INTO CUSTOMER_TB1 VALUES (CUSTOMER_ID_SEQ.NEXTVAL, 'Ajay Kumar', 7654321098, 'ajay.k@example.com', 5);
INSERT INTO CUSTOMER_TB1 VALUES (CUSTOMER_ID_SEQ.NEXTVAL, 'Ajay Kumar', 7654321098, 'ajay.k@example.com', 3);
INSERT INTO CUSTOMER_TB1 VALUES (CUSTOMER_ID_SEQ.NEXTVAL, 'Varun', 8925173580, 'varun52@example.com', 4);

CREATE SEQUENCE TRANSACTION_ID_SEQ
increment by 1
start with 1
maxvalue 150
nocache
nocycle;

CREATE TABLE TRANSACTION_TB1(
TRANS_ID NUMBER(3),
TRANS_DATE DATE,
PRINCIPLE_AMOUNT NUMBER(10),
RATE_OF_INTEREST NUMBER(5,4),
NO_OF_TENURE NUMBER(2),
INTERSET_AMT NUMBER(10,2),
TOTAL_AMT NUMBER(10,2),
CUST_ID NUMBER(3),
CONSTRAINT FK_TRANSACTION_ID FOREIGN KEY(CUST_ID)
REFERENCES CUSTOMER_TB1(CUST_ID)
);

INSERT INTO TRANSACTION_TB1(TRANS_ID, TRANS_DATE, PRINCIPLE_AMOUNT, RATE_OF_INTEREST, NO_OF_TENURE, INTERSET_AMT, TOTAL_AMT, CUST_ID) VALUES
(TRANSACTION_ID_SEQ.NEXTVAL, TO_DATE('2024/19/11','yyyy/DD/mm'), 54782, 5.3, 1, 2903.446, 57685.45, 2);
INSERT INTO TRANSACTION_TB1(TRANS_ID, TRANS_DATE, PRINCIPLE_AMOUNT, RATE_OF_INTEREST, NO_OF_TENURE, INTERSET_AMT, TOTAL_AMT, CUST_ID) VALUES
(TRANSACTION_ID_SEQ.NEXTVAL, TO_DATE('2024/19/12','yyyy/DD/mm'), 78951, 3, 5, 11842.65, 90793.65, 2);
INSERT INTO TRANSACTION_TB1 VALUES (TRANSACTION_ID_SEQ.NEXTVAL, TO_DATE('2024-10-15', 'YYYY-MM-DD'), 35000, 4.5, 3, 4725.00, 39725.00, 3);
INSERT INTO TRANSACTION_TB1 VALUES (TRANSACTION_ID_SEQ.NEXTVAL, TO_DATE('2024-09-10', 'YYYY-MM-DD'), 92000, 6.2, 2, 11384.00, 103384.00, 4);
INSERT INTO TRANSACTION_TB1 VALUES (TRANSACTION_ID_SEQ.NEXTVAL, TO_DATE('2024-08-05', 'YYYY-MM-DD'), 64000, 4.0, 4, 10240.00, 74240.00, 5);
